matrix:
  include:
    - language: python
      python: 3.6
      script:
        - python -c 'print("Hello World!")'

    - language: r
      install:
        - Rscript -e 'install.packages(c("devtools", "testthat"))'
      script:
        - Rscript -e 'library(testthat)'

before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install ipython ipython-notebook
  - sudo -H pip install jupyter
