matrix:
  include:
    - language: python
      python: 3.6
      script:
        - pytest

    - language: r
      install:
        - Rscript -e 'install.packages(c("devtools", "testthat"))'
      script:
        - Rscript -e 'library(testthat)'
        - Rscript -e 'sapply(list.files(".", full.names=F, pattern=".[rR]$"), source)' 2>&1 >/dev/null

before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install ipython ipython-notebook pandoc
  - sudo -H pip install jupyter nbconvert pytest
  - jupyter nbconvert --to script "*.ipynb"
